name: MobSF Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mobsfscan:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 10 dakikayı geçerse otomatik iptal eder

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: '. --sarif --output results.sarif || true'

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: "code-scanning/mobsfscan"
